// Chromium の DevTools プロトコル（/json/protocol）から取り出したイベント名。
// ドメインを enable したときに、そのドメインのイベントをすべてページへ流すために使う。
export const CDP_EVENTS: Record<string, string[]> = {
  Accessibility: ["loadComplete", "nodesUpdated"],
  Animation: ["animationCanceled", "animationCreated", "animationStarted", "animationUpdated"],
  Audits: ["issueAdded"],
  Autofill: ["addressFormFilled"],
  BackgroundService: ["recordingStateChanged", "backgroundServiceEventReceived"],
  BluetoothEmulation: ["gattOperationReceived", "characteristicOperationReceived", "descriptorOperationReceived"],
  Browser: ["downloadWillBegin", "downloadProgress"],
  CSS: ["fontsUpdated", "mediaQueryResultChanged", "styleSheetAdded", "styleSheetChanged", "styleSheetRemoved", "computedStyleUpdated"],
  Cast: ["sinksUpdated", "issueUpdated"],
  DOM: ["attributeModified", "attributeRemoved", "characterDataModified", "childNodeCountUpdated", "childNodeInserted", "childNodeRemoved", "distributedNodesUpdated", "documentUpdated", "inlineStyleInvalidated", "pseudoElementAdded", "topLayerElementsUpdated", "scrollableFlagUpdated", "pseudoElementRemoved", "setChildNodes", "shadowRootPopped", "shadowRootPushed"],
  DOMStorage: ["domStorageItemAdded", "domStorageItemRemoved", "domStorageItemUpdated", "domStorageItemsCleared"],
  DeviceAccess: ["deviceRequestPrompted"],
  Emulation: ["virtualTimeBudgetExpired"],
  FedCm: ["dialogShown", "dialogClosed"],
  Fetch: ["requestPaused", "authRequired"],
  Input: ["dragIntercepted"],
  Inspector: ["detached", "targetCrashed", "targetReloadedAfterCrash"],
  LayerTree: ["layerPainted", "layerTreeDidChange"],
  Log: ["entryAdded"],
  Media: ["playerPropertiesChanged", "playerEventsAdded", "playerMessagesLogged", "playerErrorsRaised", "playerCreated"],
  Network: ["dataReceived", "eventSourceMessageReceived", "loadingFailed", "loadingFinished", "requestIntercepted", "requestServedFromCache", "requestWillBeSent", "resourceChangedPriority", "signedExchangeReceived", "responseReceived", "webSocketClosed", "webSocketCreated", "webSocketFrameError", "webSocketFrameReceived", "webSocketFrameSent", "webSocketHandshakeResponseReceived", "webSocketWillSendHandshakeRequest", "webTransportCreated", "webTransportConnectionEstablished", "webTransportClosed", "directTCPSocketCreated", "directTCPSocketOpened", "directTCPSocketAborted", "directTCPSocketClosed", "directTCPSocketChunkSent", "directTCPSocketChunkReceived", "directUDPSocketCreated", "directUDPSocketOpened", "directUDPSocketAborted", "directUDPSocketClosed", "directUDPSocketChunkSent", "directUDPSocketChunkReceived", "requestWillBeSentExtraInfo", "responseReceivedExtraInfo", "responseReceivedEarlyHints", "trustTokenOperationDone", "policyUpdated", "subresourceWebBundleMetadataReceived", "subresourceWebBundleMetadataError", "subresourceWebBundleInnerResponseParsed", "subresourceWebBundleInnerResponseError", "reportingApiReportAdded", "reportingApiReportUpdated", "reportingApiEndpointsChangedForOrigin"],
  Overlay: ["inspectNodeRequested", "nodeHighlightRequested", "screenshotRequested", "inspectModeCanceled"],
  Page: ["domContentEventFired", "fileChooserOpened", "frameAttached", "frameClearedScheduledNavigation", "frameDetached", "frameSubtreeWillBeDetached", "frameNavigated", "documentOpened", "frameResized", "frameStartedNavigating", "frameRequestedNavigation", "frameScheduledNavigation", "frameStartedLoading", "frameStoppedLoading", "downloadWillBegin", "downloadProgress", "interstitialHidden", "interstitialShown", "javascriptDialogClosed", "javascriptDialogOpening", "lifecycleEvent", "backForwardCacheNotUsed", "loadEventFired", "navigatedWithinDocument", "screencastFrame", "screencastVisibilityChanged", "windowOpen", "compilationCacheProduced"],
  Performance: ["metrics"],
  PerformanceTimeline: ["timelineEventAdded"],
  Preload: ["ruleSetUpdated", "ruleSetRemoved", "preloadEnabledStateUpdated", "prefetchStatusUpdated", "prerenderStatusUpdated", "preloadingAttemptSourcesUpdated"],
  Security: ["certificateError", "visibleSecurityStateChanged", "securityStateChanged"],
  ServiceWorker: ["workerErrorReported", "workerRegistrationUpdated", "workerVersionUpdated"],
  Storage: ["cacheStorageContentUpdated", "cacheStorageListUpdated", "indexedDBContentUpdated", "indexedDBListUpdated", "interestGroupAccessed", "interestGroupAuctionEventOccurred", "interestGroupAuctionNetworkRequestCreated", "sharedStorageAccessed", "sharedStorageWorkletOperationExecutionFinished", "storageBucketCreatedOrUpdated", "storageBucketDeleted", "attributionReportingSourceRegistered", "attributionReportingTriggerRegistered", "attributionReportingReportSent", "attributionReportingVerboseDebugReportSent"],
  Target: ["attachedToTarget", "detachedFromTarget", "receivedMessageFromTarget", "targetCreated", "targetDestroyed", "targetCrashed", "targetInfoChanged"],
  Tethering: ["accepted"],
  Tracing: ["bufferUsage", "dataCollected", "tracingComplete"],
  WebAudio: ["contextCreated", "contextWillBeDestroyed", "contextChanged", "audioListenerCreated", "audioListenerWillBeDestroyed", "audioNodeCreated", "audioNodeWillBeDestroyed", "audioParamCreated", "audioParamWillBeDestroyed", "nodesConnected", "nodesDisconnected", "nodeParamConnected", "nodeParamDisconnected"],
  WebAuthn: ["credentialAdded", "credentialDeleted", "credentialUpdated", "credentialAsserted"],
  Console: ["messageAdded"],
  Debugger: ["breakpointResolved", "paused", "resumed", "scriptFailedToParse", "scriptParsed"],
  HeapProfiler: ["addHeapSnapshotChunk", "heapStatsUpdate", "lastSeenObjectId", "reportHeapSnapshotProgress", "resetProfiles"],
  Profiler: ["consoleProfileFinished", "consoleProfileStarted", "preciseCoverageDeltaUpdate"],
  Runtime: ["bindingCalled", "consoleAPICalled", "exceptionRevoked", "exceptionThrown", "executionContextCreated", "executionContextDestroyed", "executionContextsCleared", "inspectRequested"],
};
